### ISSUE TITLE
addDefault method does not work

### ISSUE THREAD

**Issue by white-gecko** [marcosrocha85/vue-jkanban#1]
I've tried your example and click the 'Add "Default" board' button, which triggers the `addDefault` method. But it does not add anything to the board.

**Comment by marcosrocha85** [comment]
It's not "linked" yet. Indeed, I have doubt if that will be necessary when I finish jKanban "reactivity". I'm looking for a snippet of mine that can help me just right now.

**Comment by marcosrocha85** [comment]
I do not added manual "add". To do reactivity, you should add new item to your collection model like I do on [Demo App](https://github.com/marcosrocha85/vue-jkanban/blob/239f007f35fe764760e5365e3685a11ab27986c5/src/App.vue#L102)

**Comment by white-gecko** [comment]
Cool, thank you very much for the clarification.
